[destination.filesystem]
bucket_url = "" # replace with your bucket name,

[destination.filesystem.credentials]
project_id = "" # please set me up!
private_key = "" # please set me up!
client_email = "" # please set me up!

[destination.bigquery]
location = "EU"
[destination.bigquery.credentials]
project_id = "" # please set me up!
private_key = "" # please set me up!
client_email = "" # please set me up!
